import './styles.css';
import {calculate,decode,defaults,encode,type Recipe,type Result,type Yeast} from './core';

type Lang='de'|'en'|'it';
type Theme='system'|'light'|'dark';

const copy={
  de:{beta:'Praxis-Beta',title:'Canotto · 24 h Kaltgare',lead:'Eine feste, skalierbare Praxisreferenz nach Renato Bosco – keine wissenschaftlich validierte Hefeberechnung.',profile:'Reguläres Profil',profileV:'Napoletana Verace (getrennt, noch ohne automatische Hefeaussage)',amount:'Teigmenge',balls:'Teiglinge',weight:'Gewicht je Teigling',hydration:'Hydration',yeast:'Hefeform',fresh:'Frischhefe · Quellenwert',idy:'Instant-Trockenhefe · 3:1-Praxisnäherung',calc:'Berechnen',result:'Dein Teig',flour:'Mehl',water:'Wasser',salt:'Salz',process:'Fester Ablauf',pre:'50 Min. warme Vorphase',cold:'24 Std. bei 4–6 °C · als 250-g-Ballen',post:'4–6 Std. warme Schlussphase',source:'Referenz und Grenze',sourceText:'Renato Bosco – Canotto, Referenz v1. Erlaubt sind 70–75 % Hydration und reine Skalierung. Zeit, Temperatur, Salz und Prozess sind unverändert.',experimental:'Vorläufige Praxisreferenz – experimentell',copy:'Text kopieren',link:'Link kopieren',share:'Teilen',copied:'Kopiert',lang:'Sprache',theme:'Darstellung',menu:'Einstellungen öffnen',close:'Einstellungen schließen',system:'System',light:'Hell',dark:'Dunkel',license:'Lizenziert unter MPL-2.0',repository:'Zum GitHub-Repository'},
  en:{beta:'Practice beta',title:'Canotto · 24 h cold fermentation',lead:'A fixed, scalable practice reference after Renato Bosco – not a scientifically validated yeast calculation.',profile:'Regular profile',profileV:'Napoletana Verace (separate, no automatic yeast claim yet)',amount:'Dough amount',balls:'Dough balls',weight:'Weight per ball',hydration:'Hydration',yeast:'Yeast form',fresh:'Fresh yeast · source value',idy:'Instant dry yeast · declared 3:1 approximation',calc:'Calculate',result:'Your dough',flour:'Flour',water:'Water',salt:'Salt',process:'Fixed process',pre:'50 min warm pre-phase',cold:'24 h at 4–6 °C · as 250 g balls',post:'4–6 h warm final phase',source:'Reference and boundary',sourceText:'Renato Bosco – Canotto, reference v1. Only 70–75% hydration and proportional scaling are allowed. Time, temperature, salt and process stay fixed.',experimental:'Preliminary practice reference – experimental',copy:'Copy text',link:'Copy link',share:'Share',copied:'Copied',lang:'Language',theme:'Appearance',menu:'Open settings',close:'Close settings',system:'System',light:'Light',dark:'Dark',license:'Licensed under MPL-2.0',repository:'Go to GitHub repository'},
  it:{beta:'Beta pratica',title:'Canotto · 24 h di maturazione a freddo',lead:'Un riferimento pratico fisso e scalabile secondo Renato Bosco, non un calcolo del lievito convalidato scientificamente.',profile:'Profilo regolare',profileV:'Napoletana Verace (separata, ancora senza indicazione automatica del lievito)',amount:'Quantità d’impasto',balls:'Panetti',weight:'Peso per panetto',hydration:'Idratazione',yeast:'Tipo di lievito',fresh:'Lievito fresco · valore della fonte',idy:'Lievito secco istantaneo · approssimazione pratica 3:1',calc:'Calcola',result:'Il tuo impasto',flour:'Farina',water:'Acqua',salt:'Sale',process:'Procedimento fisso',pre:'50 min di riposo iniziale al caldo',cold:'24 ore a 4–6 °C · in panetti da 250 g',post:'4–6 ore finali a temperatura ambiente',source:'Riferimento e limiti',sourceText:'Renato Bosco – Canotto, riferimento v1. Sono consentite solo un’idratazione del 70–75% e la scalatura proporzionale. Tempi, temperatura, sale e procedimento restano invariati.',experimental:'Riferimento pratico preliminare – sperimentale',copy:'Copia testo',link:'Copia link',share:'Condividi',copied:'Copiato',lang:'Lingua',theme:'Aspetto',menu:'Apri impostazioni',close:'Chiudi impostazioni',system:'Sistema',light:'Chiaro',dark:'Scuro',license:'Distribuito con licenza MPL-2.0',repository:'Vai al repository GitHub'}
} as const;
type Copy={ [K in keyof typeof copy.de]: string };

let lang:Lang=(['de','en','it'].includes(safeGet('lang')||'')?safeGet('lang'):'de') as Lang;
let theme:Theme=(['system','light','dark'].includes(safeGet('theme')||'')?safeGet('theme'):'system') as Theme;
let recipe:Recipe=decode(location.search)||defaults;
let result:Result|null=null;

function safeGet(k:string){try{return localStorage.getItem('pc-'+k)}catch{return null}}
function safeSet(k:string,v:string){try{localStorage.setItem('pc-'+k,v)}catch{}}
const f=(n:number,d=0)=>new Intl.NumberFormat(lang,{minimumFractionDigits:d,maximumFractionDigits:d}).format(n);
const langIcon=(value:Lang)=>value==='de'?'🇩🇪':value==='it'?'🇮🇹':'<span class="split-flag" aria-hidden="true"><span>🇬🇧</span><span>🇺🇸</span></span>';

function render(){
  document.documentElement.lang=lang;
  document.documentElement.dataset.theme=theme;
  const t=copy[lang];
  document.querySelector('#app')!.innerHTML=`<header><details class="menu"><summary aria-label="${t.menu}"><span class="hamburger" aria-hidden="true"></span></summary><div class="menu-panel"><label>${t.lang}<span class="select-with-icon"><span class="current-language">${langIcon(lang)}</span><select id="lang" aria-label="${t.lang}"><option value="de">Deutsch</option><option value="en">English</option><option value="it">Italiano</option></select></span></label><label>${t.theme}<select id="theme"><option value="system">${t.system}</option><option value="light">${t.light}</option><option value="dark">${t.dark}</option></select></label></div></details><a class="brand" href="${location.pathname}">PizzaCalc</a></header><main><section class="hero"><span class="pill">${t.beta}</span><h1>${t.title}</h1><p>${t.lead}</p></section><aside class="profile"><strong>${t.profile}</strong><span>${t.profileV}</span></aside><div class="grid"><form id="form" class="card"><h2>${t.amount}</h2><div class="fields"><label>${t.balls}<input id="balls" type="number" min="1" max="50" step="1" value="${recipe.balls}" required></label><label>${t.weight}<span class="unit"><input id="weight" type="number" min="100" max="500" step="1" value="${recipe.ballWeight}" required><b>g</b></span></label><label>${t.hydration}<span class="unit"><input id="hydration" type="number" min="70" max="75" step="0.1" value="${recipe.hydration}" required><b>%</b></span></label><label>${t.yeast}<select id="yeast"><option value="fresh">${t.fresh}</option><option value="idy">${t.idy}</option></select></label></div><button>${t.calc}</button></form><section class="card process"><h2>${t.process}</h2><ol><li>${t.pre}</li><li>${t.cold}</li><li>${t.post}</li></ol></section></div>${resultView(t)}<section class="boundary"><h2>${t.source}</h2><p>${t.sourceText}</p><a href="https://boscorenato.it/la-pizza-tonda-affittiamoci-un-canotto/" target="_blank" rel="noreferrer">Renato Bosco ↗</a></section></main><footer><span>${t.license}</span><span aria-hidden="true"> · </span><a href="https://github.com/gengener/pizzacalc">${t.repository}</a></footer>`;
  setValues();bind();
}
function resultView(t:Copy){if(!result)return'';const y=recipe.yeast==='fresh'?t.fresh:t.idy;return`<section class="result" aria-live="polite"><div><span class="pill">${t.experimental}</span><h2>${t.result}</h2><p>${recipe.balls} × ${f(recipe.ballWeight)} g · ${f(recipe.hydration,1)} % · ${y}</p></div><dl><div><dt>${t.flour}</dt><dd>${f(result.flour)} g</dd></div><div><dt>${t.water}</dt><dd>${f(result.water)} g</dd></div><div><dt>${t.salt}</dt><dd>${f(result.salt,1)} g</dd></div><div><dt>${t.yeast}</dt><dd>${f(result.yeast,2)} g</dd></div></dl><div class="actions"><button type="button" id="copy">${t.copy}</button><button type="button" id="link">${t.link}</button><button type="button" id="share">${t.share}</button></div></section>`}
function setValues(){(document.querySelector('#lang')as HTMLSelectElement).value=lang;(document.querySelector('#theme')as HTMLSelectElement).value=theme;(document.querySelector('#yeast')as HTMLSelectElement).value=recipe.yeast}
function bind(){document.querySelector('#lang')!.addEventListener('change',e=>{lang=(e.target as HTMLSelectElement).value as Lang;safeSet('lang',lang);render()});document.querySelector('#theme')!.addEventListener('change',e=>{theme=(e.target as HTMLSelectElement).value as Theme;safeSet('theme',theme);render()});document.querySelector('#form')!.addEventListener('submit',e=>{e.preventDefault();recipe={balls:Number((document.querySelector('#balls')as HTMLInputElement).value),ballWeight:Number((document.querySelector('#weight')as HTMLInputElement).value),hydration:Number((document.querySelector('#hydration')as HTMLInputElement).value),yeast:(document.querySelector('#yeast')as HTMLSelectElement).value as Yeast};result=calculate(recipe);history.replaceState(null,'',`${location.pathname}?${encode(recipe)}`);render()});if(!result)return;const text=()=>`${copy[lang].title}\n${copy[lang].flour}: ${f(result!.flour)} g\n${copy[lang].water}: ${f(result!.water)} g\n${copy[lang].salt}: ${f(result!.salt,1)} g\n${copy[lang].yeast}: ${f(result!.yeast,2)} g`;(document.querySelector('#copy')as HTMLButtonElement).onclick=()=>navigator.clipboard.writeText(text());(document.querySelector('#link')as HTMLButtonElement).onclick=()=>navigator.clipboard.writeText(location.href);(document.querySelector('#share')as HTMLButtonElement).onclick=()=>navigator.share?navigator.share({title:'PizzaCalc',text:text(),url:location.href}):navigator.clipboard.writeText(location.href)}
render();
